### ISSUE TITLE
Test ssh-ed25519 keys in resource_xelon_ssh_key_test 

### ISSUE THREAD

**Issue by megian** [Xelon-AG/terraform-provider-xelon#3]
Currently only ssh-rsa keys are tested. ed25519 keys are more secure should be tested as well.

They are actually working in the Xelon HQ UI.

**Comment by pavel-github** [comment]
@megian, thanks for your input. Technically it's a responsibility of SDK to test different scenarios and ssh key types.

When we'll enable acceptance tests, we'll consider it. I'm going to close the issue.
